name: "Naolib Integration"
description: "Intégration des API Naolib, le réseau de transport Nantais"
version: "0.1.0"
slug: "naolib"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
